# Generated by Django 5.2 on 2025-04-26 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0003_listingimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
