# Generated by Django 5.2 on 2025-06-15 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0004_listing_is_deleted"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="listingimage",
            options={
                "ordering": ["order", "uploaded_at"],
                "verbose_name": "İlan Resmi",
                "verbose_name_plural": "İlan Resimleri",
            },
        ),
        migrations.AddField(
            model_name="listingimage",
            name="file_size",
            field=models.PositiveIntegerField(
                blank=True, help_text="Dosya boyutu (byte cinsinden)", null=True
            ),
        ),
        migrations.AddField(
            model_name="listingimage",
            name="height",
            field=models.PositiveIntegerField(
                blank=True, help_text="Resim yüksekliği", null=True
            ),
        ),
        migrations.AddField(
            model_name="listingimage",
            name="is_primary",
            field=models.BooleanField(
                default=False, help_text="Bu resim ana resim olarak işaretlensin mi?"
            ),
        ),
        migrations.AddField(
            model_name="listingimage",
            name="large_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="listing_images/large/"
            ),
        ),
        migrations.AddField(
            model_name="listingimage",
            name="medium_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="listing_images/medium/"
            ),
        ),
        migrations.AddField(
            model_name="listingimage",
            name="order",
            field=models.PositiveIntegerField(
                default=0, help_text="Resim sırası, 0 en önde"
            ),
        ),
        migrations.AddField(
            model_name="listingimage",
            name="thumbnail",
            field=models.ImageField(
                blank=True, null=True, upload_to="listing_images/thumbnails/"
            ),
        ),
        migrations.AddField(
            model_name="listingimage",
            name="width",
            field=models.PositiveIntegerField(
                blank=True, help_text="Resim genişliği", null=True
            ),
        ),
    ]
