# Generated by Django 5.2 on 2025-06-29 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0005_alter_listingimage_options_listingimage_file_size_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="listingimage",
            name="large_image",
        ),
        migrations.RemoveField(
            model_name="listingimage",
            name="medium_image",
        ),
    ]
