# Generated by Django 5.2 on 2025-06-29 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0006_remove_listingimage_large_image_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="listingimage",
            name="thumbnail",
        ),
    ]
