# Generated by Django 5.2 on 2025-07-01 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0007_remove_listingimage_thumbnail"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="listing",
            name="city",
        ),
    ]
