# Generated by Django 5.2 on 2025-07-01 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0008_remove_listing_city"),
        ("locations", "0002_district_neighborhood_province_delete_city_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="district",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="listings",
                to="locations.district",
                verbose_name="İlçe",
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="neighborhood",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="listings",
                to="locations.neighborhood",
                verbose_name="Mahalle",
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="province",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="listings",
                to="locations.province",
                verbose_name="İl",
            ),
        ),
    ]
