# Generated by Django 5.2 on 2025-04-17 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CarBrand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Araç Markası",
                "verbose_name_plural": "Araç Markaları",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CarModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="models",
                        to="cars.carbrand",
                    ),
                ),
            ],
            options={
                "verbose_name": "Araç Modeli",
                "verbose_name_plural": "Araç Modelleri",
                "ordering": ["name"],
                "unique_together": {("brand", "name")},
            },
        ),
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveIntegerField()),
                ("mileage", models.PositiveIntegerField()),
                (
                    "fuel_type",
                    models.CharField(
                        choices=[
                            ("petrol", "Benzin"),
                            ("diesel", "Dizel"),
                            ("electric", "Elektrik"),
                            ("hybrid", "Hibrit"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "transmission",
                    models.CharField(
                        choices=[("manual", "Manuel"), ("automatic", "Otomatik")],
                        max_length=10,
                    ),
                ),
                ("color", models.CharField(max_length=50)),
                ("body_type", models.CharField(max_length=50)),
                (
                    "engine_power",
                    models.PositiveIntegerField(help_text="Motor gücü (HP)"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cars",
                        to="cars.carbrand",
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cars",
                        to="cars.carmodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Araç",
                "verbose_name_plural": "Araçlar",
                "ordering": ["-created_at"],
            },
        ),
    ]
