# Generated by Django 5.2 on 2025-04-25 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0002_alter_car_options_remove_car_created_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="CarTrim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name="car",
            name="trim",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cars",
                to="cars.cartrim",
            ),
        ),
        migrations.CreateModel(
            name="CarVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="cars.carmodel",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="cartrim",
            name="variant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trims",
                to="cars.carvariant",
            ),
        ),
        migrations.AddField(
            model_name="car",
            name="vairant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cars",
                to="cars.carvariant",
            ),
        ),
    ]
