# Generated by Django 5.2 on 2025-04-25 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0003_cartrim_car_trim_carvariant_cartrim_variant_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="car",
            old_name="vairant",
            new_name="variant",
        ),
    ]
